schema_version = "1.0.0"
id = "mio3_uv"
name = "Mio3 UV"
version = "1.5.1"
tagline = "UV Edit Assistant Tools"
maintainer = "Mio"
type = "add-on"
tags = ["UV"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/mio3io"
copyright = ["2025 Mio"]

[permissions]
files = "Imports images, nodes, and translations from the bundled files"
